services:
  bookrent.catalog:
    image: bookrent.catalog
    build:
      context: .
      dockerfile: Services/BookRent.Catalog/Dockerfile

  bookrent.user:
    image: bookrent.user
    build:
      context: .
      dockerfile: Services/BookRent.User/Dockerfile

  bookrent.renting:
    image: bookrent.renting
    build:
      context: .
      dockerfile: Services/BookRent.Renting/Dockerfile

  bookrent.identity:
    image: bookrent.identity
    build:
      context: .
      dockerfile: Services/BookRent.Identity/Dockerfile

  bookrent.gateway:
    image: bookrent.gateway
    build:
      context: .
      dockerfile: BookRent.Gateway/Dockerfile

