services:
  catalog-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: catalog-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost,1433", "-U", "sa", "-P", "Your_password123", "-C", "-Q", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s
    volumes:
      - catalog_mssqldata:/var/opt/mssql

  catalog-service:
    build:
      context: .                 
      dockerfile: Services/BookRent.Catalog/Dockerfile
    container_name: catalog-service
    depends_on:
      catalog-db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__CatalogDb: "Server=catalog-db,1433;Database=CatalogDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
    ports:
      - "8080:8080"

volumes:
  catalog_mssqldata:
